### ISSUE TITLE
Reading Gutenbertg UTF-8 file produces garbled result (non-printable characters)

### ISSUE THREAD

**Issue by jantonisito** [pdeitel/PythonDataScienceFullThrottle#1]
When reading text file from Gutenberg Project one needs to account for UTF-8 encoding:  
`blob = TextBlob(Path('RomeoAndJuliet.txt').read_text(encoding='utf-8'))`  
if `encoding='utf-8'` is skipped file read produces unprintable characters.

**Comment by pdeitel** [comment]
Hi Tom, Sorry I missed this previously. I am unable to reproduce this problem. Can you tell me more about your software setup? What operating system are you using? Best, Paul
