### ISSUE TITLE
reducing png images size in this repo "ch14" - please check if possible

### ISSUE THREAD

**Issue by kk-hiraskar** [pdeitel/PythonDataScienceFullThrottle#2]
Hello Paul,

I was practicing one of your lessons on DataScience, and when I downloaded this repo zip its near to 200 MB
and png image files, have taken big share here.
please check if it can be compressed or converted to jpg. may be it can just save some memory & time for others.

![Huge Files](https://user-images.githubusercontent.com/19647561/100976410-7b356d00-3565-11eb-91b6-ec5324c0ab7c.JPG)

Thanks,
KK

**Comment by pdeitel** [comment]
I removed a bunch of extra files.
